# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_rejected', models.BooleanField(default=False)),
                ('second_rejected', models.BooleanField(default=False)),
                ('third_rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('resident_id', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('sex', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(default='1970-01-01')),
                ('phone_number', models.CharField(default='', max_length=25)),
                ('university', models.CharField(default='', max_length=25)),
                ('major', models.CharField(default='', max_length=25)),
                ('gpa', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('ranking', models.CharField(default='', max_length=10)),
                ('comment', models.TextField(default='')),
                ('accepted', models.BooleanField(default=False)),
                ('attachment', models.FileField(upload_to='./attachment')),
                ('photo', models.ImageField(upload_to='./img')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('work_place', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('research_area', models.CharField(max_length=30)),
                ('recruit_number', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='selection',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Teachers'),
        ),
        migrations.AddField(
            model_name='selection',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Teachers'),
        ),
        migrations.AddField(
            model_name='selection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Students'),
        ),
        migrations.AddField(
            model_name='selection',
            name='third',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Teachers'),
        ),
    ]
