# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('resident_id', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('date_of_birth', models.DateField(default='1970-01-01')),
                ('phone_number', models.CharField(default='', max_length=25)),
                ('university', models.CharField(default='', max_length=25)),
                ('major', models.CharField(default='', max_length=25)),
                ('gpa', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('ranking', models.CharField(default='', max_length=10)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('work_place', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('research_area', models.CharField(max_length=30)),
                ('recruit_number', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
