# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSmatching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='attachment',
            field=models.FileField(null=True, upload_to='./attachment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(null=True, upload_to='./img'),
        ),
    ]
