# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSmatching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='file',
            field=models.FileField(null=True, upload_to='./upload/'),
        ),
    ]
