# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSmatching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_rejected', models.BooleanField(default=False)),
                ('second_rejected', models.BooleanField(default=False)),
                ('third_rejected', models.BooleanField(default=False)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Teachers')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Teachers')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Students')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSmatching.Teachers')),
            ],
        ),
    ]
