# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TSmatching', '0002_students_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='file',
            new_name='attachment',
        ),
    ]
