# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSmatching', '0003_auto_20170716_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
