# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('resident_id', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('date_of_birth', models.DateField(default='1970-01-01')),
                ('phone_number', models.CharField(max_length=25, null=True)),
                ('university', models.CharField(max_length=25, null=True)),
                ('major', models.CharField(max_length=25, null=True)),
                ('gpa', models.FloatField(null=True)),
                ('ranking', models.FloatField(null=True)),
                ('comment', models.TextField(null=True)),
                ('attachment', models.FileField(null=True, upload_to='attachment/%Y/%m/%d/')),
                ('first_teacher', models.ManyToManyField(null=True, related_name='teacher1', to='teacher.Teachers')),
                ('second_teacher', models.ManyToManyField(null=True, related_name='teacher2', to='teacher.Teachers')),
                ('third_teacher', models.ManyToManyField(null=True, related_name='teacher3', to='teacher.Teachers')),
            ],
        ),
    ]
