# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_teacher', models.ManyToManyField(related_name='teacher1', to='teacher.Teachers')),
                ('second_teacher', models.ManyToManyField(related_name='teacher2', to='teacher.Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('university', models.CharField(max_length=25)),
                ('gpa', models.FloatField()),
                ('ranking', models.FloatField()),
                ('comment', models.TextField()),
                ('attachment', models.FileField(upload_to='attachment/%Y/%m/%d/')),
                ('first_teacher', models.CharField(max_length=20)),
                ('second_teacher', models.CharField(max_length=20)),
                ('third_teacher', models.CharField(max_length=20)),
                ('usr_name', models.CharField(default='test', max_length=15, primary_key=True, serialize=False)),
                ('usr_pwd', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEdit',
            fields=[
                ('students_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.Students')),
            ],
            bases=('student.students',),
        ),
        migrations.AddField(
            model_name='selection',
            name='student',
            field=models.ManyToManyField(related_name='student', to='student.Students'),
        ),
        migrations.AddField(
            model_name='selection',
            name='third_teacher',
            field=models.ManyToManyField(related_name='teacher3', to='teacher.Teachers'),
        ),
    ]
