# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='attachment',
            field=models.FileField(upload_to='attachment/%Y/%m/%d/'),
        ),
    ]
