# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='resident_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
