# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_students_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='students',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='gpa',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='major',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='students',
            name='ranking',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(default='', max_length=25),
        ),
    ]
